#!/bin/tcsh -xef

echo "auto-generated by afni_proc.py, Thu Oct 10 17:24:44 2019"
echo "(version 6.34, April 25, 2019)"
echo "execution started: `date`"

# to execute via tcsh: 
#   tcsh -xef /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/MixedQuest_Ses4.tcsh |& tee /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/output.MixedQuest_Ses4.tcsh
# to execute via bash: 
#   tcsh -xef /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/MixedQuest_Ses4.tcsh 2>&1 | tee /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/output.MixedQuest_Ses4.tcsh

3dDeconvolve -input /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/INET003_Mixed_r13.scale+tlrc.HEAD /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/INET003_Mixed_r14.scale+tlrc.HEAD /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/INET003_Mixed_r15.scale+tlrc.HEAD /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/INET003_Mixed_r16.scale+tlrc.HEAD \
    -polort 4                                                                 \
    -local_times                                                              \
    -num_stimts 20                                                            \
    -stim_times 1 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_abs_corr.txt 'TENT(0,16.5,15)'               \
    -stim_label 1 AbsCon_abs_corr                                             \
    -stim_times 2 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_amb.txt 'TENT(0,16.5,15)'                    \
    -stim_label 2 AbsCon_amb                                                  \
    -stim_times 3 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_con_corr.txt 'TENT(0,16.5,15)'               \
    -stim_label 3 AbsCon_con_corr                                             \
    -stim_times 4 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_endcue.txt 'TENT(0,16.5,15)'                 \
    -stim_label 4 AbsCon_endcue                                               \
    -stim_times 5 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_error.txt 'TENT(0,16.5,15)'                  \
    -stim_label 5 AbsCon_error                                                \
    -stim_times 6 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_startcue.txt 'TENT(0,16.5,15)'               \
    -stim_label 6 AbsCon_startcue                                             \
    -stim_times 7 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/AbsCon_sustained.txt 'EXPR(0,104.4)1'               \
    -stim_label 7 AbsCon_sustained                                            \
    -stim_times 8 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/MR_endcue.txt 'TENT(0,16.5,15)'                     \
    -stim_label 8 MR_endcue                                                   \
    -stim_times 9 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/MR_error.txt 'TENT(0,16.5,15)'                      \
    -stim_label 9 MR_error                                                    \
    -stim_times 10 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/MR_mirror_corr.txt 'TENT(0,16.5,15)'               \
    -stim_label 10 MR_mirror_corr                                             \
    -stim_times 11 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/MR_same_corr.txt 'TENT(0,16.5,15)'                 \
    -stim_label 11 MR_same_corr                                               \
    -stim_times 12 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/MR_startcue.txt 'TENT(0,16.5,15)'                  \
    -stim_label 12 MR_startcue                                                \
    -stim_times 13 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/MR_sustained.txt 'EXPR(0,104.4)1'                  \
    -stim_label 13 MR_sustained                                               \
    -stim_times 14 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_amb.txt 'TENT(0,16.5,15)'                    \
    -stim_label 14 Rhyme_amb                                                  \
    -stim_times 15 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_endcue.txt 'TENT(0,16.5,15)'                 \
    -stim_label 15 Rhyme_endcue                                               \
    -stim_times 16 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_error.txt 'TENT(0,16.5,15)'                  \
    -stim_label 16 Rhyme_error                                                \
    -stim_times 17 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_no_corr.txt 'TENT(0,16.5,15)'                \
    -stim_label 17 Rhyme_no_corr                                              \
    -stim_times 18 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_startcue.txt 'TENT(0,16.5,15)'               \
    -stim_label 18 Rhyme_startcue                                             \
    -stim_times 19 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_sustained.txt 'EXPR(0,104.4)1'               \
    -stim_label 19 Rhyme_sustained                                            \
    -stim_times 20 /projects/b1081/member_directories/dmsmith/Analysis_Test/Mixed_Model_Test/INET003/stimuli_ses4/Rhyme_yes_corr.txt 'TENT(0,16.5,15)'               \
    -stim_label 20 Rhyme_yes_corr                                             \
    -iresp 1 iresp_AbsCon_abs_corr.ses4                                      \
    -iresp 2 iresp_AbsCon_amb.ses4                                           \
    -iresp 3 iresp_AbsCon_con_corr.ses4                                      \
    -iresp 4 iresp_AbsCon_endcue.ses4                                        \
    -iresp 5 iresp_AbsCon_error.ses4                                         \
    -iresp 6 iresp_AbsCon_startcue.ses4                                      \
    -iresp 8 iresp_MR_endcue.ses4                                            \
    -iresp 9 iresp_MR_error.ses4                                             \
    -iresp 10 iresp_MR_mirror_corr.ses4                                      \
    -iresp 11 iresp_MR_same_corr.ses4                                        \
    -iresp 12 iresp_MR_startcue.ses4                                         \
    -iresp 14 iresp_Rhyme_amb.ses4                                           \
    -iresp 15 iresp_Rhyme_endcue.ses4                                        \
    -iresp 16 iresp_Rhyme_error.ses4                                         \
    -iresp 17 iresp_Rhyme_no_corr.ses4                                       \
    -iresp 18 iresp_Rhyme_startcue.ses4                                      \
    -iresp 20 iresp_Rhyme_yes_corr.ses4                                      \
    -num_glt 19                                                               \
    -gltsym 'SYM: +.05*AbsCon_abs_corr[3..7] +.05*AbsCon_amb[3..7] +.05*AbsCon_con_corr[3..7]   \
    +.05*AbsCon_endcue[3..7] +.05*AbsCon_error[3..7] +.05*AbsCon_startcue[3..7]                 \
    +.05*AbsCon_sustained +.05*MR_endcue[3..7] +.05*MR_error[3..7] +.05*MR_mirror_corr[3..7]    \
    +.05*MR_same_corr[3..7] +.05*MR_startcue[3..7] +.05*MR_sustained +.05*Rhyme_amb[3..7]       \
    +.05*Rhyme_endcue[3..7] +.05*Rhyme_error[3..7] +.05*Rhyme_no_corr[3..7] +.05*Rhyme_startcue[3..7] \
    +.05*Rhyme_sustained +.05*Rhyme_yes_corr[3..7]'                                 \
    -glt_label 1 Task_Effect                                                  \
    -gltsym 'SYM: +.167*AbsCon_abs_corr[3..7] +.167*AbsCon_con_corr[3..7]                 \
    +.167*MR_mirror_corr[3..7] +.167*MR_same_corr[3..7] +.167*Rhyme_no_corr[3..7]               \
    +.167*Rhyme_yes_corr[3..7]'                                                     \
    -glt_label 2 Correct_Effect                                               \
    -gltsym 'SYM: +.33*AbsCon_error[3..7] +.33*MR_error[3..7] +.33*Rhyme_error[3..7]'           \
    -glt_label 3 Error_Effect                                                 \
    -gltsym 'SYM: +.33*AbsCon_sustained +.33*MR_sustained                     \
    +.33*Rhyme_sustained'                                                     \
    -glt_label 4 Sustained_Effect                                             \
    -gltsym 'SYM: +.167*AbsCon_endcue[3..7] +.167*AbsCon_startcue[3..7] +.167*MR_endcue[3..7]   \
    +.167*MR_startcue[3..7] +.167*Rhyme_endcue[3..7] +.167*Rhyme_startcue[3..7]'                \
    -glt_label 5 All_Cue_Effect                                               \
    -gltsym 'SYM: +.167*MR_endcue[3..7] +.167*MR_error[3..7] +.167*MR_mirror_corr[3..7]         \
    +.167*MR_same_corr[3..7] +.167*MR_startcue[3..7] +.167*MR_sustained'                  \
    -glt_label 6 MR_Effect                                                    \
    -gltsym 'SYM: +.143*Rhyme_amb[3..7] +.143*Rhyme_endcue[3..7] +.143*Rhyme_error[3..7]        \
    +.143*Rhyme_no_corr[3..7] +.143*Rhyme_startcue[3..7] +.143*Rhyme_sustained            \
    +.143*Rhyme_yes_corr[3..7]'                                                     \
    -glt_label 7 Rhyme_Effect                                                 \
    -gltsym 'SYM: +.5*MR_mirror_corr[3..7] +.5*MR_same_corr[3..7]'                        \
    -glt_label 8 MR_Correct_Effect                                            \
    -gltsym 'SYM: +.5*Rhyme_no_corr[3..7] +.5*Rhyme_yes_corr[3..7]'                       \
    -glt_label 9 Rhyme_Correct_Effect                                         \
    -gltsym 'SYM: +.5*MR_endcue[3..7] +.5*MR_startcue[3..7]'                              \
    -glt_label 10 MR_Cue_Effect                                               \
    -gltsym 'SYM: +.5*Rhyme_endcue[3..7] +.5*Rhyme_startcue[3..7]'                        \
    -glt_label 11 Rhyme_Cue_Effect                                            \
    -gltsym 'SYM: -.167*AbsCon_abs_corr[3..7] -.167*AbsCon_con_corr[3..7]                 \
    +.33*AbsCon_error[3..7] +.33*MR_error[3..7] -.167*MR_mirror_corr[3..7] -.167*MR_same_corr[3..7]   \
    +.33*Rhyme_error[3..7] -.167*Rhyme_no_corr[3..7] -.167*Rhyme_yes_corr[3..7]'                \
    -glt_label 12 ErrorMinusCorrect_Effect                                    \
    -gltsym 'SYM: -.25*AbsCon_abs_corr[3..7] +.5*AbsCon_amb[3..7] -.25*AbsCon_con_corr[3..7]    \
    +.5*Rhyme_amb[3..7] -.25*Rhyme_no_corr[3..7] -.25*Rhyme_yes_corr[3..7]'                     \
    -glt_label 13 AmbMinusCorrect_Effect                                      \
    -gltsym 'SYM: +.5*AbsCon_amb[3..7] +.5*Rhyme_amb[3..7]'                               \
    -glt_label 14 Am_Effect                                                   \
    -gltsym 'SYM: +.143*AbsCon_amb[3..7] +.143*AbsCon_abs_corr[3..7]                      \
    +.143*AbsCon_con_corr[3..7] +.143*AbsCon_endcue[3..7] +.143*AbsCon_error[3..7]              \
    +.143*AbsCon_startcue[3..7] +.143*AbsCon_sustained'                             \
    -glt_label 15 AbsCon_Effect                                               \
    -gltsym 'SYM: +.5*AbsCon_abs_corr[3..7] +.5*AbsCon_con_corr[3..7]'                    \
    -glt_label 16 AbsCon_Correct_Effect                                       \
    -gltsym 'SYM: +.5*AbsCon_endcue[3..7] +.5*AbsCon_startcue[3..7]'                      \
    -glt_label 17 AbsCon_Cue_Effect                                           \
    -gltsym 'SYM: +.33*AbsCon_startcue[3..7] +.33*MR_startcue[3..7] +.33*Rhyme_startcue[3..7]'  \
    -glt_label 18 StartCue_Effect                                             \
    -gltsym 'SYM: +.33*AbsCon_endcue[3..7] +.33*MR_endcue[3..7] +.33*Rhyme_endcue[3..7]'        \
    -glt_label 19 Endcue_Effect                                               \
    -float                                                                    \
    -jobs 4                                                                   \
    -fout -tout -x1D X.xmatses4.1D -xjpeg Xses4.jpg                                   \
    -fitts fitts.ses4                                                        \
    -errts errts.ses4                                                      \
    -bucket stats.ses4